title: En riktig titel
author: Asterdroid =)
email: me@asterdroid.github.io
description: > # this means to ignore newlines until "baseurl:"
 An awesome description for my site here!

# social links
twitter_username: @sterdroid
github_username:  asterdroid

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
